cat("Loading libraries and attaching Crossover namespace\n")
library(Crossover)
library(MASS)
library(multcomp)
attach(loadNamespace("Crossover"), name="namespace:Crossover", pos=3, warn.conflicts=FALSE)
