cat("Loading libraries and load_all Crossover.\n")
library(Crossover)
library(MASS)
library(multcomp)
library(devtools)
load_all("pkg/Crossover/")
#attach(loadNamespace("Crossover"), name="namespace:Crossover", pos=3, warn.conflicts=FALSE)
